### PR TITLE
Creating a fork and applying @alex88's fix to the zombie process issue

### PR DESCRIPTION
**Pull request by mkorfmann**
Please consider merging this pull request, we had some problems on our servers with defunct phantomjs processes and @alex88's modifications to def execute fix these problems.

Cheers and have a good day,
Manuel Korfmann

### CODE REVIEW

**Comment by westoque** [comment]
@mkorfmann Thanks. Will check it out. Looks like a test is failing.

**Comment by alex88** [comment]
Seems like because you're using rspec's `its` which has been removed in rspec 3 https://github.com/rspec/rspec-its. You should set a version lock on the gemfile spec for rsepc.

**Comment by westoque** [comment]
@alex88 Thanks. Doing it now.

**Comment by westoque** [comment]
@mkorfmann Can you please pull latest from master, rebase, and the spec should pass. Then we should  be able to merge it. Thanks.

**Comment by mkorfmann** [comment]
Yes, will do that asap.

**Comment by mkorfmann** [comment]
Done.

**Comment by westoque** [comment]
@mkorfmann Sweet! Thanks.

Closes #12

**Pull request merged**
