### PR TITLE
Allow phantomjs.rb receiving passing options to phantomjs directly.

### PR DESCRIPTION
**Pull request by nachogiljaldo**
I tried to keep it as few invasive as possible, thus, I just allowed creating your own instance using the parameters as an option.
Also, regarding the test, that's the best test I could come up with, but I know this could be a false positive in the feature if Airbnb's ssl would change. Ideas are welcome.

### CODE REVIEW

**Comment by westoque** [comment]
@nachogiljaldo Maybe we can change the test to use other options that won't turn out to be false positives? Like `--version` or something similar? What do you think?

Thanks.

**Comment by nachogiljaldo** [comment]
Sure, sounds as a good idea, I was so focused on my ssl problem that forgot there were other parameters :D. Will fix it during the weekend.

**Comment by nachogiljaldo** [comment]
@westoque changed

**Comment by Loremaster** [comment]
That is not merged? :( Why?

**Comment by nachogiljaldo** [comment]
@westoque any chances you could merge this? It seems some people needs it.

**Comment by westoque** [comment]
@Loremaster @nachogiljaldo sorry for the delay, merged :+1:

**Comment by Loremaster** [comment]
@westoque Thanks you!

**Pull request merged**
